### ISSUE TITLE
Won't open in Eagle 6 or 7 ?

### ISSUE THREAD

**Issue by mr-sneezy** [adafruit/Adafruit-2.2-SPI-TFT#1]
Not sure if I'm doing something wrong, but the sch & brd files won't open in either version of Eagle I have. Eagle reports "Not an Eagle file".

**Comment by ladyada** [comment]
it works fine, you're not downloading them right or something

**Comment by mr-sneezy** [comment]
Might be. I just did 'right click' then 'save link as'.
